#!/bin/bash
#
##simple Password Generator !!!!

echo "This is a simple password generator "
echo "Please enter the lenght of the passwords: "
read PASS_LENGTH

for p in $(seq 1 ): #if you want 5 passwords add seq1 5
do
        openssl rand -base64 48 | cut -c1-$PASS_LENGTH
done

